version: '3.3'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    env_file:
      - ./.env

  web:
    image: dyojinn/foodgram-backend:v1.2022
    volumes:
      - static_backend:/app/static/
      - media_backend:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_files:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/ # local ../docs/:/usr/share/nginx/html/api/docs/ # remote ./docs/:/usr/share/nginx/html/api/docs/
      - static_backend:/var/html/static_backend/
      - media_backend:/var/html/media_backend/
    depends_on:
      - web

  frontend:
    image: dyojinn/foodgram-frontend:v1.2022
    volumes:
      - frontend_files:/app/result_build/

volumes:
  postgres_data:
  frontend_files:
  static_backend:
  media_backend:
