# Generated by Django 3.2.15 on 2022-10-14 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_ingredient_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='ingredient_id',
            new_name='ingredient',
        ),
        migrations.RenameField(
            model_name='ingredientrecipe',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='tagrecipe',
            old_name='recipe_id',
            new_name='recipe',
        ),
        migrations.RenameField(
            model_name='tagrecipe',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
