# Generated by Django 3.2.15 on 2022-10-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20221014_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='amount',
            name='amount',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
