# Generated by Django 3.2.15 on 2022-10-28 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20221028_1715'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_recipe',
        ),
    ]
