# Generated by Django 3.2.15 on 2022-10-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20221028_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'verbose_name_plural': 'favorites'},
        ),
    ]
