# Generated by Django 3.2.15 on 2022-10-28 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_favorite_unique_user_recipe'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_user_recipe',
        ),
    ]
